### ISSUE TITLE
Do not display no references found for anonymous TypeScript functions

### ISSUE THREAD

**Issue by huksley** [kisstkondoros/typelens#37]
Hi!

I am using TypeLens 1.6.5 + TypeScript 3.2.2 + VSCode 1.30.1
For inner anonymous function I have following output which is not very comfortable.
As inner function can`t be used really in any other place, is there a way to disable displaying `no references found`?

![image](https://user-images.githubusercontent.com/1594349/54090539-e1379500-437d-11e9-8d63-16cf64eec054.png)

**Comment by kisstkondoros** [comment]
Thanks for reporting the issue, it should be fixed in the version 1.6.6 which was just published.

**Comment by robrecord** [comment]
This isn't fixed when using in the PHP language - I still get "no referenced found".

**Comment by kisstkondoros** [comment]
@robrecord could you provide a code sample?
